#!/usr/bin/env python3

import argparse, socket, time, json, select, random
import enum

BROADCAST = "FFFF"
HEARTBEAT_PERIOD = .140  # leader should send heartbeat every 140ms
REPLICAS = 5

class State(enum.Enum):
    FOLLOWER = 0
    CANDIDATE = 1
    LEADER = 2

class Replica:
    # universal fields
    state = State.FOLLOWER  # current state of this replica
    term = 0  # current term
    leader_id = BROADCAST  # current leader of the cluster

    log = []  # list of triples: [term, k, v]
    data = {}  # dict of committed (k, v) pairs
    timer_start = 0

    election_queue = []  # client messages received during an election period to be serviced later
    election = False

    commitIndex = -1  # the index of the biggest committed entry in log

    # follower fields:
    voted = False  # flag for if weve voted in the election yet
    TIMEOUT = None  # our timeout threshold in ms

    # candidate fields:
    my_voters = []  # our votees, including ourself

    # leader fields:
    curr_client = None  # the current client being serviced by the put()
    curr_mid = None  # the current message id being serviced by the put()
    awaiting_majority = False  # flag for whether this put() is awaiting quorum
    successes = 0  # number of followers who've agree to the current put
    puts_queue = []  # the queue of future client put()s
    put_timer = 0
    curr_put = None
    curr_k_v = [None, None]  # the current (k,v) pair to be put()

    def __init__(self, port, id, others):
        self.port = port
        self.id = id
        self.others = others


        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('localhost', 0))

        print("Replica %s starting up" % self.id, flush=True)
        hello = { "src": self.id, "dst": BROADCAST, "leader": BROADCAST, "type": "hello" }
        self.send(hello)

        # assign timeout within 150–300ms
        self.TIMEOUT = random.randrange(150, 300) / 1000
        self.timer_start = time.time()

    def run(self):
        while True:
            incoming, outgoing, exceptional = select.select([self.socket], [self.socket], [self.socket])
            for reader in incoming:
                if reader is self.socket:
                    # recv
                    data, addr = self.socket.recvfrom(65535)
                    msg = json.loads(data.decode('utf-8'))
                    print("Received message '%s'" % (data.decode('utf-8'),), flush=True)
                    mtype = msg['type']
                    src = msg['src']

                    # handle a requestVote RPC
                    if mtype == "rv":
                        self.got_request_vote(msg)

                    # handle a vote
                    if mtype == "vote" and self.state == State.CANDIDATE:
                        self.got_vote(msg)

                    # handle an appendEntries RPC
                    if mtype == 'ae':
                        self.got_append_entries(msg)

                    # handle client put/get
                    if mtype == 'put':
                        if self.election:
                            self.election_queue.append(msg)
                        else:
                            self.handle_put(msg)

                    # handle client put/get
                    if mtype == 'get':
                        if self.election:
                            self.election_queue.append(msg)
                        else:
                            self.handle_get(msg)

                    # handle a follower response to AppendEntries
                    if mtype == 'ae_res' and self.state == State.LEADER:
                        self.got_ae_res(msg)

            for writer in outgoing:
                if writer is self.socket:
                    # Check for various timeouts, depending on state
                    if self.state != State.LEADER:
                        self.check_timeout()
                    if self.state == State.LEADER:
                        self.check_heartbeat()
                        if self.awaiting_majority and time.time() > (self.put_timer + 50/1000):
                            self.send_append_entries()
                            self.put_timer = time.time()

    def send(self, message):
        print("Sent message: %s" % message, flush=True)
        self.socket.sendto(json.dumps(message).encode('utf-8'), ('localhost', self.port))

    # received a RequestVote RPC
    def got_request_vote(self, json_msg):

        if self.state != State.LEADER:
            self.election = True
            src = json_msg['src']
            valid = True


            # 1. Reply false if term < currentTerm (§5.1)
            if json_msg['term'] <= self.term:
                valid = False

            # 2. Cannot vote twice (§5.2)
            if self.voted:
                valid = False

            # 3. If candidate’s log is at least as up-to-date as receiver’s log, grant vote (§5.4)
            # ie. it is guaranteed that the election winner will have most up to date logs
            src_last_i = json_msg['last_i']
            src_last_term = json_msg['last_term']

            last_i = len(self.log) - 1
            last_term = -1 if self.log == [] else self.log[last_i][0]

            if src_last_i < last_i or src_last_term < last_term:
                valid = False

            if valid:
                self.leader_id = BROADCAST


            votemsg = {
                "src": self.id,
                "dst": src,
                "leader": BROADCAST if valid else self.leader_id,
                "type": "vote",
                "vote": 'true' if valid else 'false',
                "cand_id": src,
            }

            self.send(votemsg)
            self.voted = valid


    # if not the leader, monitor leader timeout
    def check_timeout(self):
        if time.time() > (self.timer_start + self.TIMEOUT) and self.state == State.FOLLOWER:

            # become a candidate, increment our term, send RequestVote
            self.leader_id = BROADCAST
            self.state = State.CANDIDATE
            self.term += 1
            self.election = True


            last_i = len(self.log) - 1
            last_term = -1 if self.log == [] else self.log[last_i][0]
            rv = { 
                "src": self.id, 
                "dst": BROADCAST, 
                "leader": BROADCAST,
                "type": "rv", 
                "term": self.term, 
                "last_i": last_i,         # index of last log entry
                "last_term": last_term    # term of that entry
            }
            self.voted = True
            self.send(rv)
            self.my_voters = [self.id]
            self.TIMEOUT = random.randrange(150, 300) / 1000
            self.timer_start = time.time()
            
        if time.time() > (self.timer_start + self.TIMEOUT) and self.state == State.CANDIDATE:
            self.term += 1

            last_i = len(self.log) - 1
            last_term = -1 if self.log == [] else self.log[last_i][0]
            rv = {
                "src": self.id,
                "dst": BROADCAST,
                "leader": BROADCAST,
                "type": "rv",
                "term": self.term,
                "last_i": last_i,  # index of last log entry
                "last_term": last_term  # term of that entry
            }
            self.voted = True
            self.send(rv)
            self.my_voters = [self.id]
            self.TIMEOUT = random.randrange(150, 300) / 1000
            self.timer_start = time.time()

    # if leader, monitor heartbeat
    def check_heartbeat(self):
        if time.time() > (self.timer_start + HEARTBEAT_PERIOD):
            self.send_append_entries(heartbeat = True)


    # inform followers of new log entries via AppendEntries RPC
    def send_append_entries(self, heartbeat = False):
        # "index of entry immediately preceding new ones". right now we always only add 1 at a time, so this will always be len(log) - 2.
        prev_log_i = len(self.log) - 2                                             # SECOND to last index in log

        prev_log_term = -1 if len(self.log) <= 1 else self.log[prev_log_i][0]       # term of that entry

        entries = [] if self.log == [] else self.log[prev_log_i+1:]                 # everything after prev_log_i in the log

        ae = {
            "src": self.id, 
            "dst": BROADCAST, 
            "leader": self.id,
            "type": "ae",
            "term": self.term,
            "prev_log_i": prev_log_i,
            "prev_log_term": prev_log_term,
            "entries": [] if heartbeat else entries, 
            "commit": self.commitIndex
            }
        self.timer_start = time.time()
        self.send(ae)

    # if candidate, parse the vote we received
    def got_vote(self, msg):
        if self.state == State.LEADER:
            return # already leader, ignore
        voter = msg['src']
        if msg['vote'] == 'true' and (voter not in self.my_voters):
            self.my_voters.append(voter)
            # if we have a majority, we are now the leader
            if len(self.my_voters) >= 3:
                self.state = State.LEADER
                self.leader_id = self.id
                self.voted = False
                self.election = False
                self.my_voters = []
                # start heartbeat as new leader
                self.send_append_entries(heartbeat = True)
                self.handleElectionQueue()  # go through backlog messages that happened during the election



    # logic for getting an appendEntries RPC
        # if new leader, update fields
        # reconcile your logs with theirs
        # accept or reject
    def got_append_entries(self, msg):
        self.timer_start = time.time()
        leader = msg["src"]
        entries = msg["entries"]

        # if this is a new leader
        if self.leader_id == BROADCAST or self.state == State.LEADER:
            self.state = State.FOLLOWER
            self.leader_id = leader
            self.voted = False
            self.election = False
            self.term = msg["term"]
            self.my_voters = [] # in case you had also been running for election
            self.handleElectionQueue() # go through backlog messages that happened during the election
        
        # if not just a heartbeat
        if entries != []:

            valid = True

            prev_log_i = int(msg["prev_log_i"])  # -1 if leaders log len < 2
            self_prev_log_i = len(self.log) - 1  # last index in log

            if self_prev_log_i > prev_log_i:
                valid = False

            if valid:
                self.log.append(entries)
                self.data[entries[0][1]] = entries[0][2]
                self.commitIndex = msg["prev_log_i"] + 1

            ae_res = { 
                "src": self.id, 
                "dst": leader, 
                "leader": leader,
                "type": "ae_res",
                "term": self.term,
                "index": msg["prev_log_i"],
                "success": "True" if valid else "False"
                }
            self.send(ae_res)

    # execute the client requests waiting in the queue from the election period
    def handleElectionQueue(self):

        for msg in self.election_queue:
            mtype = msg['type']
            if mtype == 'put':
                self.handle_put(msg)

            # handle client put/get
            if mtype == 'get':
                self.handle_get(msg)
        self.election_queue = []

    # handle success or failure response from follower after an appendEntries RPC
    def got_ae_res(self, msg):

        success = msg["success"]
        index = msg['index']
        if success == "True" and index == self.commitIndex:
            self.successes += 1
            if self.successes >= 2:

                # grab the most recent entry, commit to data dict
                entry = self.log[len(self.log) - 1]
                self.data[entry[1]] = entry[2] 

                # tell the client we've committed their put()
                put_ok = {
                    "src": self.id, 
                    "dst": self.curr_client,
                    "leader": self.id, 
                    "type": "ok", 
                    "MID": self.curr_mid,
                    }
                self.send(put_ok)
                self.commitIndex += 1
                self.awaiting_majority = False
                self.successes = 0  # reset successes counter

                # if more put()s are in the queue
                if self.puts_queue != []:
                    next_put_msg = self.puts_queue[0]
                    self.puts_queue.remove(next_put_msg)
                    self.puts_logic(next_put_msg)         # kick off next put() 

        elif success == "False":
            return

    # if awaiting majority for the current put, add it to queue, else inform replicas
    def handle_put(self, msg):
        # if client doesn't know who the leader is
        if self.state != State.LEADER: # msg['leader'] == BROADCAST or msg['leader'] != self.leader_id:
            redirect = {
                "src": self.id, 
                "dst": msg["src"],
                "leader": self.leader_id,
                "type": "redirect",
                "MID": msg['MID']
                }
            self.send(redirect)
            return
        # otherwise, if we are the leader, append to log and tell replicas
        if self.state == State.LEADER:
            # if we have not yet responded to the current put(), add this put() to queue
            if self.awaiting_majority:
                self.puts_queue.append(msg)
                return
            self.puts_logic(msg)                

    # leader logic for informing replicas about put() from client
    def puts_logic(self, msg):
        # if non duplicate put()
        if [msg["key"], msg["value"]] != self.curr_k_v:

            # 1. keep track of MID and client for our response
            self.curr_mid = msg['MID']
            self.curr_client = msg['src']

            # 2. form the new log entry
            entry = [self.term, msg["key"], msg["value"]]
            self.log.append(entry)

            # 3. inform replicas, wait for majority successes
            self.send_append_entries()
            self.awaiting_majority = True
            self.put_timer = time.time()

    # leader logic for replying to a get()
    def handle_get(self, msg):
        # if we have committed the key to our dict, return the value

        if self.state != State.LEADER: # msg['leader'] == BROADCAST or msg['leader'] != self.leader_id:

            redirect = {
                "src": self.id,
                "dst": msg["src"],
                "leader": self.leader_id,
                "type": "redirect",
                "MID": msg['MID']
                }
            self.send(redirect)
            return
        if msg["key"] in self.data.keys():
            val = self.data[msg["key"]]
            get_ok = {
                "src": self.id, 
                "dst": msg["src"], 
                "leader": self.id, 
                "type": "ok", 
                "MID": msg["MID"],
                "value": val
                }
            self.send(get_ok)
        else:
            get_failure = {
                "src": self.id, 
                "dst": msg["src"], 
                "leader": self.id, 
                "type": "fail", 
                "MID": msg["MID"]
                }
            self.send(get_failure)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='run a key-value store')
    parser.add_argument('port', type=int, help="Port number to communicate")
    parser.add_argument('id', type=str, help="ID of this replica")
    parser.add_argument('others', metavar='others', type=str, nargs='+', help="IDs of other replicas")
    args = parser.parse_args()
    replica = Replica(args.port, args.id, args.others)
    replica.run()
